#!/usr/bin/env python
#
# Copyright 2008 David Anderson
#
# Redistribution of this file is permitted under
# the terms of the GNU Public License (GPL) version 2.

import sys
from pyweb.pywebgen import main

sys.exit(main())
